# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2879fab0d762a1276cbaeab6f41dbb617f12da3382a3d18bfe6b7725dfcee24904da08307de87c5945e4bb619375fc7ff3426e5c077b6e0dde0917e9f5fbf80b

test:
  secret_key_base: bec89c06856740416ff78abb0dca99a8eeba4964f771d2e1dbab4887963054d043a8e83668ec25c94683f10c4faedbb3058b74ad2854a9ff6c6d6852da855e65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
